### ISSUE TITLE
In the quiz for #10 This is not a valid expression.

### ISSUE THREAD

**Issue by victoriagrows-xx** [learn-co-students/programming-univbasics-1-quiz-online-web-prework#1]
In the quiz for #10 This is not a valid expression. 

#10
"The expression below evaluates to: 3 + 6 (2)"

**Comment by maxwellbenton** [comment]
Hi @victoriagrows,

Thank you for spotting this and providing feedback. We've updated this quiz question (added the missing `*`) so that the expression is valid and evaluates to the expected quiz answer.

Thank you for contributing to a Learn.co lesson!

**Comment by victoriagrows-xx** [comment]
Great!
